# Generated by Django 3.1.7 on 2021-02-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='isbn',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
